# Language is R
language: r
warnings_are_errors: true
sudo: false
cache: packages

# Operating systems to build on ------
matrix:
  include:
    - os: linux
      dist: xenial
      r: release
    - os: osx
      osx_image: xcode12
      r: release
    - os: linux
      dist: xenial
      r: devel
    - os: osx 
      osx_image: xcode12
      r: devel 
      
# Branches
branches:
  only:
  - main
  - devel

after_success:
  - Rscript -e 'covr::codecov()'

# If anyone else would like to be added to notifications,
# just add your email below!
notifications:
  email:
    - jones@biology.sdu.dk
    - levisc8@gmail.com
    
