name: Build pkgdown site

on:
  push:
    branches:
      - devel
      #- master
  pull_request:
    branches:
      #- master
      #- devel

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install XQuartz
        if: runner.os == 'macOS'
        run: |
          wget https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
          sudo hdiutil attach XQuartz-2.7.11.dmg
          sudo installer -package /Volumes/XQuartz-2.7.11/XQuartz.pkg -target / 
        
      - name: Build the site
        run: |
          install.packages("textshaping",type = "binary",dependencies = TRUE)
          install.packages("devtools")
          devtools::install(pkg = ".", dependencies = TRUE)
          install.packages("rmarkdown",dependencies = TRUE)
          rmarkdown::render(input = "README.Rmd","github_document",clean = TRUE)
          unlink("README.html")
          install.packages("pkgdown", dependencies = TRUE)    
          pkgdown::build_site()
        shell: Rscript {0}

      - name: Commit README and site files to github
        run: |
          git init
          git fetch
          git add docs/
          git add README.md
          git commit -m 'Re-build site and README' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

      - name: Session info
        run: |
          options(width = 100)
          sessionInfo()
        shell: Rscript {0}

      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: devel-02-codemeta
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'